import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  content: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 44, maxWidth: 760, width: '100%', alignSelf: 'center' },
  topRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  title: { color: colors.text, fontSize: 36, lineHeight: 40, fontWeight: '900', letterSpacing: -1.4 },
  subtitle: { color: colors.muted, fontSize: 16, lineHeight: 24, marginTop: 8 },
  sectionTitle: { color: colors.text, fontSize: 14, fontWeight: '900', letterSpacing: 1.2, marginBottom: 10 },
  eyebrow: { color: colors.accent, fontSize: 10, fontWeight: '900', letterSpacing: 2.1 },
  card: { backgroundColor: colors.surface, borderRadius: 22, borderWidth: 1, borderColor: colors.border, padding: 16 },
  button: { minHeight: 56, borderRadius: 17, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
  buttonPrimary: { backgroundColor: colors.accent },
  buttonSecondary: { backgroundColor: colors.surface2, borderWidth: 1, borderColor: colors.border },
  buttonText: { color: colors.bg, fontSize: 16, fontWeight: '900' },
  buttonTextSecondary: { color: colors.text, fontSize: 16, fontWeight: '800' },
  statCard: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 15 },
  glowCard: { backgroundColor: colors.surface2, borderRadius: 28, borderWidth: 1, borderColor: colors.borderStrong, padding: 22 },
  homeHeader: { flexDirection:'row', alignItems:'center', justifyContent:'space-between' },
  iconButton: { width:44, height:44, borderRadius:22, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.border, alignItems:'center', justifyContent:'center' },
  hero: { alignItems:'center', paddingTop:30 },
  heroKicker: { color:colors.accent, fontSize:10, fontWeight:'900', letterSpacing:2, textAlign:'center' },
  heroTitle: { color:colors.text, fontSize:42, lineHeight:46, fontWeight:'900', letterSpacing:-1.7, marginTop:8, textAlign:'center' },
  heroSubtitle: { color:colors.muted, fontSize:15, lineHeight:22, textAlign:'center', maxWidth:420, marginTop:8 },
  heroArt: { height:205, width:'100%', maxWidth:390, alignItems:'center', justifyContent:'flex-end', marginTop:4, position:'relative' },
  heroBook: { width:190, height:74, borderRadius:30, backgroundColor:'#171821', borderWidth:1, borderColor:colors.accent, alignItems:'center', justifyContent:'center', shadowColor:colors.accent, shadowOpacity:.22, shadowRadius:28 },
  floatingCard: { position:'absolute', width:58, height:78, borderRadius:16, backgroundColor:colors.surface3, borderWidth:1, borderColor:colors.borderStrong, alignItems:'center', justifyContent:'center', bottom:62 },
  floatingIcon: { color:colors.accent2, fontSize:28, fontWeight:'900' },
  playButton: { marginTop:18, minHeight:88, borderRadius:26, backgroundColor:colors.accent, paddingHorizontal:20, flexDirection:'row', alignItems:'center', gap:15 },
  playIcon: { width:48, height:48, borderRadius:16, backgroundColor:'rgba(11,11,13,.12)', alignItems:'center', justifyContent:'center' },
  playTitle: { color:colors.bg, fontSize:27, fontWeight:'900', letterSpacing:1 },
  playSubtitle: { color:colors.bg, opacity:.75, fontSize:12, fontWeight:'700', marginTop:2 },
  quickCard: { marginTop:12, minHeight:68, borderRadius:21, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.border, padding:12, flexDirection:'row', alignItems:'center', gap:12 },
  quickIcon: { width:44, height:44, borderRadius:15, backgroundColor:colors.bg, alignItems:'center', justifyContent:'center' },
  quickTitle: { color:colors.text, fontSize:16, fontWeight:'900' },
  quickSubtitle: { color:colors.muted, fontSize:12, marginTop:2 },
  homeGrid: { flexDirection:'row', gap:9, marginTop:12 },
  homeTile: { flex:1, minHeight:120, borderRadius:20, backgroundColor:colors.surface, borderWidth:1, borderColor:colors.border, padding:13, alignItems:'center', justifyContent:'center' },
  tileIcon: { fontSize:24, marginBottom:7 },
  tileTitle: { color:colors.text, fontSize:13, fontWeight:'900', textAlign:'center' },
  tileSubtitle: { color:colors.muted, fontSize:10, marginTop:3, textAlign:'center' },
  homeTagline: { flexDirection:'row', alignItems:'center', gap:10, marginVertical:27 },
  tagLine: { flex:1, height:1, backgroundColor:colors.border },
  tagText: { color:colors.stone, fontSize:9, fontWeight:'900', letterSpacing:2, textAlign:'center' },
  downloadCard: { backgroundColor:colors.surface2, borderRadius:22, borderWidth:1, borderColor:colors.border, padding:16 },
  downloadTitle: { color:colors.text, fontSize:17, fontWeight:'900', marginTop:7 },
  downloadText: { color:colors.muted, fontSize:12.5, lineHeight:19, marginTop:5 },
  downloadMini: { backgroundColor:colors.bg, borderRadius:14, padding:12 },
  downloadMiniLabel: { color:colors.accent, fontSize:9, fontWeight:'900', letterSpacing:1.5 },
  downloadMiniText: { color:colors.muted, fontSize:11.5, marginTop:4 },
  downloadButton: { minHeight:48, borderRadius:14, backgroundColor:colors.accent, alignItems:'center', justifyContent:'center' },
  disclaimer: { color:colors.muted, fontSize:10.5, lineHeight:17, textAlign:'center', marginTop:22 },
  setupHeader: { flexDirection:'row', alignItems:'center' },
  backText: { color:colors.text, fontSize:36, lineHeight:36 },
  setupHeaderTitle: { color:colors.text, fontSize:25, fontWeight:'900', marginTop:3 },
  setupStep: { color:colors.accent, fontSize:13, fontWeight:'900' },
  choiceGrid: { flexDirection:'row', gap:9 },
  choiceCard: { flex:1, minHeight:78, borderRadius:19, backgroundColor:colors.surface, borderWidth:1, borderColor:colors.border, alignItems:'center', justifyContent:'center' },
  choiceCardActive: { backgroundColor:colors.accent, borderColor:colors.accent },
  choiceNumber: { color:colors.text, fontSize:25, fontWeight:'900' },
  choiceLabel: { color:colors.muted, fontSize:10, fontWeight:'800', marginTop:1 },
  cardRow: { marginTop:10, minHeight:62, paddingHorizontal:15, paddingVertical:12, borderRadius:18, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.border, flexDirection:'row', alignItems:'center' },
  rowTitle: { color:colors.text, fontSize:14, fontWeight:'900' },
  rowSubtitle: { color:colors.muted, fontSize:11.5, lineHeight:17, marginTop:3 },
  linkText: { color:colors.accent2, fontSize:12, fontWeight:'900' },
  input: { backgroundColor:colors.bg, borderColor:colors.border, borderWidth:1, borderRadius:14, paddingHorizontal:13, height:48, color:colors.text, fontSize:14, fontWeight:'700' },
  durationGrid: { flexDirection:'row', flexWrap:'wrap', gap:9 },
  durationCard: { width:'48%', flexGrow:1, minHeight:82, borderRadius:19, backgroundColor:colors.surface, borderWidth:1, borderColor:colors.border, padding:13 },
  durationNumber: { color:colors.text, fontSize:22, fontWeight:'900' },
  durationUnit: { color:colors.muted, fontSize:9, fontWeight:'900', letterSpacing:1.3, marginTop:-2 },
  durationHint: { color:colors.muted, fontSize:11, fontWeight:'700', marginTop:8 },
  autoCard: { marginTop:13, padding:14, borderRadius:20, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.borderStrong, flexDirection:'row', alignItems:'center', gap:12 },
  autoBadge: { width:38, height:38, borderRadius:13, backgroundColor:colors.accent, alignItems:'center', justifyContent:'center' },
  customizeBar: { marginTop:12, minHeight:64, paddingHorizontal:15, paddingVertical:10, borderRadius:18, backgroundColor:colors.surface, borderWidth:1, borderColor:colors.border, flexDirection:'row', alignItems:'center', justifyContent:'space-between' },
  helper: { color:colors.muted, fontSize:11.5, lineHeight:17, marginBottom:9 },
  wrapRow: { flexDirection:'row', flexWrap:'wrap', gap:8 },
  filterChip: { minHeight:42, paddingHorizontal:12, borderRadius:14, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.border, justifyContent:'center' },
  filterChipActive: { backgroundColor:colors.accent, borderColor:colors.accent },
  filterChipText: { color:colors.text, fontSize:11.5, fontWeight:'800' },
  smallChoice: { flex:1, minHeight:44, borderRadius:13, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.border, alignItems:'center', justifyContent:'center' },
  smallChoiceActive: { backgroundColor:colors.accent, borderColor:colors.accent },
  smallChoiceText: { color:colors.text, fontSize:11.5, fontWeight:'800' },
  modeGroupLabel: { color:colors.accent, fontSize:9, fontWeight:'900', letterSpacing:1.5, marginBottom:7 },
  modeChip: { flexDirection:'row', alignItems:'center', gap:6, minHeight:40, paddingHorizontal:11, borderRadius:13, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.border },
  modeChipActive: { backgroundColor:colors.accent, borderColor:colors.accent },
  modeChipIcon: { color:colors.accent2, fontSize:12, fontWeight:'900' },
  modeChipText: { color:colors.text, fontSize:11.5, fontWeight:'800' },
  startSummary: { marginTop:22, padding:16, borderRadius:21, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.borderStrong },
  summaryTitle: { color:colors.text, fontSize:21, fontWeight:'900', marginTop:5 },
  summaryText: { color:colors.muted, fontSize:12, marginTop:4 },
  helperCenter: { color:colors.stone, fontSize:10.5, textAlign:'center', marginTop:10 },
});
