import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: 'transparent' },
  content: { paddingHorizontal: 22, paddingTop: 20, paddingBottom: 128, maxWidth: 720, width: '100%', alignSelf: 'center' },
  topRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  title: { color: '#FFFDF5', fontSize: 36, lineHeight: 40, fontWeight: '900', letterSpacing: -1.1 },
  subtitle: { color: '#EAF5F1', fontSize: 14, lineHeight: 21, marginTop: 7 },
  sectionTitle: { color: '#FFFDF5', fontSize: 12, fontWeight: '900', letterSpacing: 1.8, marginBottom: 10 },
  eyebrow: { color: colors.accent, fontSize: 10, fontWeight: '900', letterSpacing: 2.1 },
  card: { backgroundColor: 'rgba(4, 35, 43, 0.62)', borderRadius: 26, borderWidth: 1, borderColor: 'rgba(121,213,232,0.52)', padding: 17, shadowColor: '#00151B', shadowOpacity: 0.34, shadowRadius: 22 },
  button: { minHeight: 60, borderRadius: 21, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20, borderWidth: 1 },
  buttonPrimary: { backgroundColor: '#F2C94C', borderColor: '#FFEAA0', shadowColor: '#F2C94C', shadowOpacity: .42, shadowRadius: 20 },
  buttonSecondary: { backgroundColor: 'rgba(3, 36, 44, .66)', borderColor: 'rgba(121,213,232,.55)' },
  buttonText: { color: colors.bg, fontSize: 16, fontWeight: '900' },
  buttonTextSecondary: { color: '#F7FBF8', fontSize: 15, fontWeight: '900' },
  statCard: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 15 },
  glowCard: { backgroundColor: 'rgba(3, 30, 38, .70)', borderRadius: 30, borderWidth: 1, borderColor: 'rgba(242,201,76,.58)', padding: 22, shadowColor: '#00151B', shadowOpacity: .36, shadowRadius: 24 },
  homeHeader: { flexDirection:'row', alignItems:'center', justifyContent:'space-between' },
  iconButton: { width:44, height:44, borderRadius:22, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.border, alignItems:'center', justifyContent:'center' },
  hero: { alignItems:'center', paddingTop:30 },
  heroKicker: { color:colors.accent, fontSize:10, fontWeight:'900', letterSpacing:2, textAlign:'center' },
  heroTitle: { color:colors.text, fontSize:42, lineHeight:46, fontWeight:'900', letterSpacing:-1.7, marginTop:8, textAlign:'center' },
  heroSubtitle: { color:colors.muted, fontSize:15, lineHeight:22, textAlign:'center', maxWidth:420, marginTop:8 },
  heroArt: { height:205, width:'100%', maxWidth:390, alignItems:'center', justifyContent:'flex-end', marginTop:4, position:'relative' },
  heroBook: { width:190, height:74, borderRadius:30, backgroundColor:'#171821', borderWidth:1, borderColor:colors.accent, alignItems:'center', justifyContent:'center', shadowColor:colors.accent, shadowOpacity:.22, shadowRadius:28 },
  floatingCard: { position:'absolute', width:58, height:78, borderRadius:16, backgroundColor:colors.surface3, borderWidth:1, borderColor:colors.borderStrong, alignItems:'center', justifyContent:'center', bottom:62 },
  floatingIcon: { color:colors.accent2, fontSize:28, fontWeight:'900' },
  playButton: { marginTop:18, minHeight:88, borderRadius:26, backgroundColor:colors.accent, paddingHorizontal:20, flexDirection:'row', alignItems:'center', gap:15 },
  playIcon: { width:48, height:48, borderRadius:16, backgroundColor:'rgba(11,11,13,.12)', alignItems:'center', justifyContent:'center' },
  playTitle: { color:colors.bg, fontSize:27, fontWeight:'900', letterSpacing:1 },
  playSubtitle: { color:colors.bg, opacity:.75, fontSize:12, fontWeight:'700', marginTop:2 },
  quickCard: { marginTop:12, minHeight:68, borderRadius:21, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.border, padding:12, flexDirection:'row', alignItems:'center', gap:12 },
  quickIcon: { width:44, height:44, borderRadius:15, backgroundColor:colors.bg, alignItems:'center', justifyContent:'center' },
  quickTitle: { color:colors.text, fontSize:16, fontWeight:'900' },
  quickSubtitle: { color:colors.muted, fontSize:12, marginTop:2 },
  homeGrid: { flexDirection:'row', gap:9, marginTop:12 },
  homeTile: { flex:1, minHeight:120, borderRadius:20, backgroundColor:colors.surface, borderWidth:1, borderColor:colors.border, padding:13, alignItems:'center', justifyContent:'center' },
  tileIcon: { fontSize:24, marginBottom:7 },
  tileTitle: { color:colors.text, fontSize:13, fontWeight:'900', textAlign:'center' },
  tileSubtitle: { color:colors.muted, fontSize:10, marginTop:3, textAlign:'center' },
  homeTagline: { flexDirection:'row', alignItems:'center', gap:10, marginVertical:27 },
  tagLine: { flex:1, height:1, backgroundColor:colors.border },
  tagText: { color:colors.stone, fontSize:9, fontWeight:'900', letterSpacing:2, textAlign:'center' },
  downloadCard: { backgroundColor:colors.surface2, borderRadius:22, borderWidth:1, borderColor:colors.border, padding:16 },
  downloadTitle: { color:colors.text, fontSize:17, fontWeight:'900', marginTop:7 },
  downloadText: { color:colors.muted, fontSize:12.5, lineHeight:19, marginTop:5 },
  downloadMini: { backgroundColor:colors.bg, borderRadius:14, padding:12 },
  downloadMiniLabel: { color:colors.accent, fontSize:9, fontWeight:'900', letterSpacing:1.5 },
  downloadMiniText: { color:colors.muted, fontSize:11.5, marginTop:4 },
  downloadButton: { minHeight:48, borderRadius:14, backgroundColor:colors.accent, alignItems:'center', justifyContent:'center' },
  disclaimer: { color:colors.muted, fontSize:10.5, lineHeight:17, textAlign:'center', marginTop:22 },
  setupHeader: { flexDirection:'row', alignItems:'center' },
  backText: { color:colors.text, fontSize:36, lineHeight:36 },
  setupHeaderTitle: { color:colors.text, fontSize:25, fontWeight:'900', marginTop:3 },
  setupStep: { color:colors.accent, fontSize:13, fontWeight:'900' },
  choiceGrid: { flexDirection:'row', gap:9 },
  choiceCard: { flex:1, minHeight:98, borderRadius:21, backgroundColor:'rgba(3,31,38,0.60)', borderWidth:1, borderColor:'rgba(121,213,232,0.42)', alignItems:'center', justifyContent:'center', shadowColor:'#000', shadowOpacity:0.18, shadowRadius:12 },
  choiceCardActive: { backgroundColor:colors.accent, borderColor:colors.accent, shadowColor:colors.accent, shadowOpacity:0.42, shadowRadius:18 },
  choiceNumber: { color:colors.text, fontSize:25, fontWeight:'900' },
  choiceLabel: { color:colors.muted, fontSize:10, fontWeight:'800', marginTop:1 },
  cardRow: { marginTop:10, minHeight:62, paddingHorizontal:15, paddingVertical:12, borderRadius:18, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.border, flexDirection:'row', alignItems:'center' },
  rowTitle: { color:colors.text, fontSize:14, fontWeight:'900' },
  rowSubtitle: { color:colors.muted, fontSize:11.5, lineHeight:17, marginTop:3 },
  linkText: { color:colors.accent2, fontSize:12, fontWeight:'900' },
  input: { backgroundColor:colors.bg, borderColor:colors.border, borderWidth:1, borderRadius:14, paddingHorizontal:13, height:48, color:colors.text, fontSize:14, fontWeight:'700' },
  durationGrid: { flexDirection:'row', flexWrap:'wrap', gap:9 },
  durationCard: { width:'48%', flexGrow:1, minHeight:102, borderRadius:21, backgroundColor:'rgba(3,31,38,0.60)', borderWidth:1, borderColor:'rgba(121,213,232,0.42)', padding:15 },
  durationNumber: { color:colors.text, fontSize:22, fontWeight:'900' },
  durationUnit: { color:colors.muted, fontSize:9, fontWeight:'900', letterSpacing:1.3, marginTop:-2 },
  durationHint: { color:colors.muted, fontSize:11, fontWeight:'700', marginTop:8 },
  autoCard: { marginTop:14, padding:15, borderRadius:22, backgroundColor:'rgba(3,42,46,0.62)', borderWidth:1, borderColor:colors.borderStrong, flexDirection:'row', alignItems:'center', gap:12 },
  autoBadge: { width:38, height:38, borderRadius:13, backgroundColor:colors.accent, alignItems:'center', justifyContent:'center' },
  customizeBar: { marginTop:13, minHeight:70, paddingHorizontal:16, paddingVertical:11, borderRadius:21, backgroundColor:'rgba(3,31,38,0.62)', borderWidth:1, borderColor:'rgba(121,213,232,0.34)', flexDirection:'row', alignItems:'center', justifyContent:'space-between' },
  helper: { color:colors.muted, fontSize:11.5, lineHeight:17, marginBottom:9 },
  wrapRow: { flexDirection:'row', flexWrap:'wrap', gap:8 },
  filterChip: { minHeight:42, paddingHorizontal:12, borderRadius:14, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.border, justifyContent:'center' },
  filterChipActive: { backgroundColor:colors.accent, borderColor:colors.accent },
  filterChipText: { color:colors.text, fontSize:11.5, fontWeight:'800' },
  smallChoice: { flex:1, minHeight:44, borderRadius:13, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.border, alignItems:'center', justifyContent:'center' },
  smallChoiceActive: { backgroundColor:colors.accent, borderColor:colors.accent },
  smallChoiceText: { color:colors.text, fontSize:11.5, fontWeight:'800' },
  modeGroupLabel: { color:colors.accent, fontSize:9, fontWeight:'900', letterSpacing:1.5, marginBottom:7 },
  modeChip: { flexDirection:'row', alignItems:'center', gap:6, minHeight:40, paddingHorizontal:11, borderRadius:13, backgroundColor:colors.surface2, borderWidth:1, borderColor:colors.border },
  modeChipActive: { backgroundColor:colors.accent, borderColor:colors.accent },
  modeChipIcon: { color:colors.accent2, fontSize:12, fontWeight:'900' },
  modeChipText: { color:colors.text, fontSize:11.5, fontWeight:'800' },
  startSummary: { marginTop:22, padding:16, borderRadius:21, backgroundColor:'rgba(4,49,51,0.80)', borderWidth:1, borderColor:colors.borderStrong },
  summaryTitle: { color:colors.text, fontSize:21, fontWeight:'900', marginTop:5 },
  summaryText: { color:colors.muted, fontSize:12, marginTop:4 },
  helperCenter: { color:colors.stone, fontSize:10.5, textAlign:'center', marginTop:10 },

  flowContent: { paddingHorizontal: 22, paddingTop: 18, paddingBottom: 128, width: '100%', maxWidth: 720, alignSelf: 'center' },
  flowContentReady: { paddingHorizontal: 22, paddingTop: 18, paddingBottom: 128, width: '100%', maxWidth: 640, alignSelf: 'center' },
  flowHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 58 },
  flowBack: { width: 42, height: 42, borderRadius: 21, backgroundColor: 'rgba(3,32,39,.58)', borderWidth: 1, borderColor: 'rgba(255,255,255,.25)', alignItems: 'center', justifyContent: 'center' },
  flowBackText: { color: colors.white, fontSize: 34, lineHeight: 34, marginTop: -4 },
  flowTitle: { color: colors.white, fontSize: 32, lineHeight: 34, fontWeight: '900', letterSpacing: -.7, marginTop: 2 },
  flowSubtitle: { color: '#F3F8F5', fontSize: 14, lineHeight: 21, marginTop: 9, marginBottom: 26 },
  stepBadge: { width: 43, height: 43, borderRadius: 15, backgroundColor: 'rgba(4,35,40,.68)', borderWidth: 1, borderColor: 'rgba(242,201,76,.55)', alignItems: 'center', justifyContent: 'center' },
  stepBadgeText: { color: colors.accent2, fontSize: 13, fontWeight: '900' },
  flowSection: { color: colors.white, fontSize: 14, fontWeight: '900', letterSpacing: 1.6, marginBottom: 11 },
  teamChoiceGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  teamChoice: { width: '48%', minHeight: 142, borderRadius: 22, backgroundColor: 'rgba(3,31,38,.72)', borderWidth: 1, borderColor: 'rgba(121,213,232,.48)', padding: 15, alignItems: 'center', justifyContent: 'center' },
  teamChoiceActive: { backgroundColor: colors.accent, borderColor: '#FFE58A', shadowColor: colors.accent, shadowOpacity: .55, shadowRadius: 20 },
  teamChoiceOptional: { backgroundColor: 'rgba(43,28,75,.68)', borderColor: 'rgba(194,167,240,.65)' },
  teamChoiceIcon: { fontSize: 28, marginBottom: 4 },
  teamChoiceNumber: { color: colors.white, fontSize: 27, fontWeight: '900' },
  teamChoiceLabel: { color: colors.muted, fontSize: 11, fontWeight: '800', marginTop: 1 },
  teamChoiceOptionalTitle: { color: colors.white, fontSize: 16, fontWeight: '900', marginTop: 4 },
  flowInfoCard: { marginTop: 13, minHeight: 74, padding: 13, borderRadius: 20, backgroundColor: 'rgba(3,43,48,.72)', borderWidth: 1, borderColor: 'rgba(121,213,232,.40)', flexDirection: 'row', alignItems: 'center', gap: 11 },
  infoIcon: { width: 43, height: 43, borderRadius: 15, backgroundColor: 'rgba(3,28,36,.85)', alignItems: 'center', justifyContent: 'center' },
  infoTitle: { color: colors.white, fontSize: 14, fontWeight: '900' },
  infoSubtitle: { color: '#D9E7E0', fontSize: 11.5, lineHeight: 17, marginTop: 3 },
  infoAction: { color: colors.accent2, fontSize: 12, fontWeight: '900' },
  renamePanel: { marginTop: 8, padding: 12, gap: 8, borderRadius: 18, backgroundColor: 'rgba(2,25,31,.78)', borderWidth: 1, borderColor: colors.border },
  flowInput: { height: 46, borderRadius: 13, borderWidth: 1, borderColor: 'rgba(121,213,232,.35)', backgroundColor: 'rgba(8,48,54,.72)', color: colors.white, paddingHorizontal: 13, fontWeight: '700' },
  flowHintCard: { marginTop: 13, minHeight: 82, padding: 14, borderRadius: 21, backgroundColor: 'rgba(7,53,52,.76)', borderWidth: 1, borderColor: 'rgba(242,201,76,.50)', flexDirection: 'row', alignItems: 'center', gap: 12 },
  goldIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center' },
  flowPrimaryButton: { marginTop: 16, minHeight: 62, borderRadius: 21, backgroundColor: colors.accent, borderWidth: 1, borderColor: '#FFE58A', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, shadowColor: colors.accent, shadowOpacity: .42, shadowRadius: 20 },
  flowPrimaryText: { color: colors.bg, fontSize: 17, fontWeight: '900' },
  flowPrimaryArrow: { position: 'absolute', right: 20, color: colors.bg, fontSize: 31, lineHeight: 31, fontWeight: '400' },
  flowFooter: { color: 'rgba(240,247,243,.72)', textAlign: 'center', fontSize: 10.5, marginTop: 11 },
  durationChoiceGrid: { gap: 10 },
  durationChoice: { minHeight: 98, borderRadius: 21, backgroundColor: 'rgba(3,31,38,.74)', borderWidth: 1, borderColor: 'rgba(121,213,232,.45)', padding: 13, flexDirection: 'row', alignItems: 'center', gap: 12 },
  durationChoiceActive: { backgroundColor: colors.accent, borderColor: '#FFE58A', shadowColor: colors.accent, shadowOpacity: .48, shadowRadius: 18 },
  durationIcon: { color: colors.accent2, fontSize: 26, width: 37, textAlign: 'center' },
  durationChoiceNumber: { color: colors.white, fontSize: 25, lineHeight: 25, fontWeight: '900' },
  durationChoiceUnit: { color: colors.muted, fontSize: 9, letterSpacing: 1.4, fontWeight: '900' },
  durationChoiceTitle: { color: colors.white, fontSize: 14, fontWeight: '900' },
  durationChoiceSub: { color: colors.muted, fontSize: 10.5, marginTop: 3 },
  autoWideCard: { marginTop: 14, minHeight: 78, padding: 13, borderRadius: 21, backgroundColor: 'rgba(4,49,51,.78)', borderWidth: 1, borderColor: 'rgba(242,201,76,.52)', flexDirection: 'row', alignItems: 'center', gap: 11 },
  autoText: { color: colors.success, fontSize: 11, fontWeight: '900', letterSpacing: 1 },
  flowSummaryCard: { marginTop: 14, padding: 16, borderRadius: 21, backgroundColor: 'rgba(2,30,36,.76)', borderWidth: 1, borderColor: 'rgba(121,213,232,.38)' },
  summaryBig: { color: colors.white, fontSize: 22, fontWeight: '900', marginTop: 5, marginBottom: 2 },
  readyBack: { width: 42, height: 42, borderRadius: 21, backgroundColor: 'rgba(3,32,39,.58)', borderWidth: 1, borderColor: 'rgba(255,255,255,.25)', alignItems: 'center', justifyContent: 'center' },
  readyTop: { alignItems: 'center', marginTop: -5 },
  readyCrown: { width: 52, height: 52, borderRadius: 18, backgroundColor: 'rgba(242,201,76,.16)', borderWidth: 1, borderColor: 'rgba(242,201,76,.52)', alignItems: 'center', justifyContent: 'center', marginTop: 12 },
  readyTitle: { color: colors.white, fontSize: 38, fontWeight: '900', letterSpacing: -1.2, marginTop: 7 },
  readySubtitle: { color: '#F0F7F4', fontSize: 14, marginTop: 5 },
  readyHero: { height: 190, alignItems: 'center', justifyContent: 'center' },
  readyCards: { flexDirection: 'row', gap: -4, padding: 13, borderRadius: 22, backgroundColor: 'rgba(2,38,45,.78)', borderWidth: 1, borderColor: 'rgba(242,201,76,.62)', shadowColor: colors.accent, shadowOpacity: .35, shadowRadius: 25 },
  readySpark: { position: 'absolute', bottom: 16, width: 92, height: 45, borderRadius: 18, backgroundColor: 'rgba(2,25,31,.88)', borderWidth: 1, borderColor: colors.accent, alignItems: 'center', justifyContent: 'center' },
  readySummary: { borderRadius: 22, backgroundColor: 'rgba(2,31,37,.78)', borderWidth: 1, borderColor: 'rgba(121,213,232,.45)', paddingHorizontal: 15, paddingVertical: 6 },
  readyRow: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 13 },
  readyIcon: { width: 38, textAlign: 'center', fontSize: 22, color: colors.accent2 },
  readyIconImage: { width: 36, height: 36, marginRight: 8 },
  readyLabel: { color: colors.muted, fontSize: 10, fontWeight: '800' },
  readyValue: { color: colors.white, fontSize: 13, fontWeight: '800', marginTop: 2 },
  readyDivider: { height: 1, backgroundColor: 'rgba(255,255,255,.13)', marginLeft: 51 },
  readySecondary: { minHeight: 49, marginTop: 9, borderRadius: 17, borderWidth: 1, borderColor: 'rgba(121,213,232,.42)', backgroundColor: 'rgba(3,34,42,.66)', alignItems: 'center', justifyContent: 'center' },
  readySecondaryText: { color: colors.white, fontSize: 13, fontWeight: '800' },
});
